id: IE294935E
legacy_id: P000552
ocr_import_info:
  bdrc_scan_id: W22130
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T08:48:38'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T20:45:17.787199+00:00'
last_modified: 2022-09-02 04:47:46.499706
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22130
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW22130
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བཞད་པའི་རྡོ་རྗེ།
  author: འོལ་དགའ་རྗེ་དྲུང ༠༣་བཞད་པའི་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.6260308880088955
  ocr_word_median_confidence_index: 0.6499999761581421
quality: null
bases:
  I5899:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5899
      total_pages: 624
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I5899.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.621338300189132
    legacy_id: v012
  I5898:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5898
      total_pages: 506
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I5898.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6192702037659202
    legacy_id: v011
  I5888:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5888
      total_pages: 752
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5888.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.61561662563284
    legacy_id: v001
  I5891:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5891
      total_pages: 528
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I5891.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6178824148340323
    legacy_id: v004
  I5893:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5893
      total_pages: 432
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I5893.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6482191841430412
    legacy_id: v006
  I5894:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5894
      total_pages: 428
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I5894.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.652801049089368
    legacy_id: v007
  I5895:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5895
      total_pages: 556
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I5895.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6747529399605523
    legacy_id: v008
  I5897:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5897
      total_pages: 510
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I5897.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6232288988996557
    legacy_id: v010
  I5896:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5896
      total_pages: 550
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I5896.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6729866708552878
    legacy_id: v009
  I5892:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5892
      total_pages: 476
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I5892.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6294154090656165
    legacy_id: v005
  I5900:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5900
      total_pages: 520
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I5900.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6311874726758896
    legacy_id: v013
  I5890:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5890
      total_pages: 604
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I5890.txt
    statistics:
      ocr_word_median_confidence_index: 0.5699999928474426
      ocr_word_mean_confidence_index: 0.5751173939166174
    legacy_id: v003
  I5889:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5889
      total_pages: 588
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I5889.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.6046369317773026
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
